### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by rvincemt** [rvmaitim/POSATWS#2]
Create ThingSpeak functionalities.

**Comment by rvmaitim** [comment]
GUI Revamp for Main

**Comment by rvmaitim** [comment]
GUI Re

**Comment by rvincemt** [comment]
Created. Forwarded for bug testing after 5 hours

**Comment by rvincemt** [comment]
Subject for bug testing

**Comment by rvincemt** [comment]
Thingspeak connection is okay, onwards to further bug testing

**Comment by rvincemt** [comment]
Found out that I can use A1-A5 as digital inputs, this could lead to more inputs. Ethernet can finally be supported!

**Comment by rvincemt** [comment]
ThingSpeak connection is up and running. Also, the sensor values are now readable.
